export const siteConfig = {
  name: "همراز قاسمی",
  nameEn: "Hamraz Ghasemi",
  title: "همراز قاسمی | مربی فیتنس قزوین",
  description:
    "همراز قاسمی، مربی حرفه‌ای TRX و فیتنس در قزوین — برنامه تمرینی اختصاصی، تغذیه ورزشی، کلاس‌های تخصصی و مشاوره آنلاین برای رسیدن به بهترین نسخه خودت.",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://hamrazghasemi.ir",
  locale: "fa_IR",
  language: "fa",
  author: "همراز قاسمی",
  authorEn: "Hamraz Ghasemi",
  authorTitle: "مربی حرفه‌ای TRX و فیتنس",
  email: "info@hamrazghasemi.ir",
  phone: "028-3333-4455",
  mobile: "09123456789",
  address: "قزوین، میدان آزادی",
  city: "قزوین",
  region: "قزوین",
  geo: {
    latitude: 36.2688,
    longitude: 50.0041,
  },
  keywords: [
    "همراز قاسمی",
    "Hamraz Ghasemi",
    "مربی فیتنس قزوین",
    "مربی شخصی قزوین",
    "مربی TRX قزوین",
    "بدنسازی قزوین",
    "تناسب اندام قزوین",
    "برنامه تمرینی",
    "تغذیه ورزشی",
    "کلاس ورزشی قزوین",
    "مربی آنلاین",
  ],
  social: {
    instagram: "https://instagram.com/hamraz.ghasemi",
    telegram: "https://t.me/hamrazghasemi",
    youtube: "https://youtube.com/@hamrazghasemi",
  },
};
